FROM golang:1.20

# Copy the entire current directory (where the Dockerfile is located) into the container
COPY . /app/

# Make your script executable
RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]
