# Policy for: .gitlab-ci.yml prof-correctness job in DataDog/apm-reliability/dd-trace-py
# Same federation surface as dd-trace-py gitlab.github-access.read (issuer +
# subject). Extra claim_pattern 403'd nightly main/4.14 (~06:00Z) while later
# same-day main pushes minted; that job runs on every main pipeline source.
issuer: https://gitlab.ddbuild.io
subject_pattern: "project_path:DataDog/apm-reliability/dd-trace-py:ref_type:(branch|tag):ref:.*"

permissions:
  actions: write
